on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to IPFS
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        id: deploy
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: /
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
